config/routes.rb
BaseSite::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  namespace :admin do
    root :to => 'home#index'
    
    match 'login' => 'home#login', :via => :get

    resources :users, :except => [:show]

    resources :static_texts, :except => [:show]

    resource :configurable
  end

  scope :module => 'front' do
    scope ':locale', locale: /#{I18n.available_locales.join('|')}/ do

      root :to => 'base#index'

      match 'signup' => 'users#new'
      match 'signup/complete' => 'users#signup_complete', :as => 'signup_complete'

      resources :sessions, :only => [:create]
      match 'login' => "sessions#new"
      match 'logout' => "sessions#destroy"
      
      match 'activate(/:activation_code)' => 'users#activate', :as => :activate_account
      match 'send_activation(/:user_id)' => 'users#send_activation', :as => :send_activation
      
      match 'forgot_password' => 'users#forgot_password', :as => :forgot_password, :via => :get
      match 'forgot_password' => 'users#forgot_password_lookup_email', :as => :forgot_password, :via => :post

      put 'reset_password/:reset_password_code' => 'users#reset_password_submit', :as => :reset_password, :via => :put
      get 'reset_password/:reset_password_code' => 'users#reset_password', :as => :reset_password, :via => :get

      resources :users

      match '*path' => 'pages#show', :as => 'page'

    end
    match '*path', to: redirect("/#{I18n.default_locale}/%{path}")
    match '', to: redirect("/#{I18n.default_locale}")
  end

end

app/controllers/admin/configurables_controller.rb
class Admin::ConfigurablesController < Admin::BaseController
  include ConfigurableEngine::ConfigurablesController

  before_filter :set_view_variables

  def set_view_variables
    @title = t :configs
    @main_menu_active = 'configs'
  end
end

app/views/admin/configurables/show.html.haml
.row-fluid
  .span9
    = form_tag(admin_configurable_path, :method => :put) do 
      - Configurable.keys.each do |key|
        - options = Configurable.defaults[key]
        - if options[:type] == 'boolean'
          .control-group.form-inline
            = hidden_field_tag key, "0" 
            = check_box_tag key, "1", Configurable.send(key)
            = label_tag key, options[:name]
        - else
          .control-group
            = label_tag key, options[:name]
            - case options[:type]
              - when 'password'
                = password_field_tag key, Configurable.send(key), :class => 'input-large'
              - when 'text'
                = text_area_tag key, Configurable.send(key), :rows => 5, :class => 'input-large'
              - when 'list'
                = text_area_tag key, Configurable.send(key).collect{ |a| a.join(",")}.join("\n"), :rows => 5, :class => 'input-xxlarge'
              - else
                = text_field_tag key, Configurable.send(key), :class => 'input-large'

      = submit_tag t(:save), :class => 'btn btn-large btn-primary'

  .span3