config/routes.rb
BaseSite::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  namespace :admin do
    root :to => 'home#index'
    
    match 'login' => 'home#login', :via => :get

    resources :users, :except => [:show]

    resources :static_texts, :except => [:show]

    resource :configurable
  end

  scope :module => 'front' do
    scope ':locale', locale: /#{I18n.available_locales.join('|')}/ do

      root :to => 'base#index'

      match 'signup' => 'users#new'
      match 'signup/complete' => 'users#signup_complete', :as => 'signup_complete'

      resources :sessions, :only => [:create]
      match 'login' => "sessions#new"
      match 'logout' => "sessions#destroy"
      
      match 'activate(/:activation_code)' => 'users#activate', :as => :activate_account
      match 'send_activation(/:user_id)' => 'users#send_activation', :as => :send_activation
      
      match 'forgot_password' => 'users#forgot_password', :as => :forgot_password, :via => :get
      match 'forgot_password' => 'users#forgot_password_lookup_email', :as => :forgot_password, :via => :post

      put 'reset_password/:reset_password_code' => 'users#reset_password_submit', :as => :reset_password, :via => :put
      get 'reset_password/:reset_password_code' => 'users#reset_password', :as => :reset_password, :via => :get

      resources :users

      match '*path' => 'pages#show', :as => 'page'

    end
    match '*path', to: redirect("/#{I18n.default_locale}/%{path}")
    match '', to: redirect("/#{I18n.default_locale}")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_and_belongs_to_many :roles

  has_secure_password

  attr_accessible :login, :email, :password, :password_confirmation
  attr_accessible :role_ids, :active, :banned, :as => :admin

  validates :login, :presence => true,
                    :format => {:with => /\A[a-z\d\-]+\z/i},
                    :length => {:within => 4..20},
                    :uniqueness => {:case_sensitive => false}

  validates :email, :presence => true,
                    :format => {:with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i},
                    :uniqueness => {:case_sensitive => false}
  
  validates :password,   :presence => true,
                        :confirmation => true,
                        :length => {:within => 4..20}, :on => :create
                        
  validates :password_confirmation, :presence => true, 
                                    :length => {:within => 4..20}, :on => :create
  
  validates_length_of :password, :within => 4..20, :allow_blank => true, :on => :update
  validates_length_of :password_confirmation, :within => 4..20, :allow_blank => true, :on => :update

  before_create {generate_token(:auth_token)}
  before_create :set_default_role

  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end

  def self.find_by_login_or_email(login_or_email)
    where("login = ? OR email = ?", login_or_email, login_or_email).first
  end

  def self.authenticate(email, password)
    find_by_email(email).try(:authenticate, password)
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
  def set_default_role
    default_role = Role.find_by_name('registered')
    self.roles << default_role
  end

  def active?
    active
  end
  
  def banned?
    banned
  end
  
  def activate
    update_attribute('active', true)
    active?
  end

  def deactivate
    update_attribute('active', false)
    active?
  end
  
  def reset_perishable_token!
    generate_token(:perishable_token)
    save :validate => false
  end

  def has_role?(role_name)
    self.roles.each do |role|
      return true if role.name == role_name.to_s
    end
    false
  end
  
  def admin?
    has_role?(:admin)
  end

  def super_admin?
    has_role?(:super_admin)
  end

  def send_activation_instructions!
    reset_perishable_token!
    Notifier.activation_instructions(self).deliver
  end
  
  def reset_password_send!
    reset_perishable_token!
    Notifier.reset_password(self).deliver
  end

  def self.find_using_perishable_token(token, age = 0)
    return nil if token.blank?
    age = age.to_i

    conditions_sql = "perishable_token = ?"
    conditions_subs = [token]

    if column_names.include?("updated_at") && age > 0
      conditions_sql += " and updated_at > ?"
      conditions_subs << age.seconds.ago
    end

    where(conditions_sql, *conditions_subs).first
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
end

app/controllers/front/users_controller.rb
class Front::UsersController < Front::BaseController
  
  filter_access_to :new, :create, :signup_complete, :activate, :forgot_password, :forgot_password_lookup_email, :reset_password, :reset_password_submit
  filter_access_to :edit, :update, :destroy, :attribute_check => true

  def index
    @users = User.all

    @title = t('users.pl')
  end

  def show
    @user = User.find(params[:id])

    @title = t('users.user_profile', :username => @user.login)
  end

  def new
    @user = User.new
    @title = t('users.signup')
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      if Configurable.confirm_registration
        @user.send_activation_instructions!   
        session[:registration_complete] = 'confirm'
      else
         @user.activate
         session[:registration_complete] = 'without_confirm'
      end
      redirect_to signup_complete_url
    else
      @title = t('users.signup')
      render 'new'
    end
  end

  def signup_complete
    not_found unless session[:registration_complete].present?
    @message = session[:registration_complete] == 'confirm' ? t('users.signup_with_confirm_complete') : t('users.signup_without_confirm_complete')
    @title = t('users.signup')
  end

  def activate
    user = User.find_using_perishable_token(params[:activation_code], 7.days) || not_found
    not_found if user.active?
    if user.activate
      flash[:success] = t('users.activation_complete')
      session[:registration_complete] = nil
      cookies[:auth_token] = user.auth_token
      redirect_to user
    else
      flash[:error] = t('failure.general')
      redirect_to root_url
    end
  end

  def edit
    @title = t('users.edit')
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = t(:saved)
      redirect_to @user
    else
      flash[:error] = @user.valid? ? t('failure.general') : t('failure.invalid_form') 
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    flash[:success] = t :deleted
    redirect_to root_url
  end

  def forgot_password   
    @title = t('users.reset_password')
  end

  def forgot_password_lookup_email
    user = User.find_by_email(params[:user][:email])
    if user
      user.reset_password_send!
      flash[:success] = "#{t('users.reset_password_sent', :email => user.email)}".html_safe
      respond_to do |format|
        format.html{redirect_to forgot_password_url}
        format.js{render}
      end  
    else
      flash[:error] = "#{t('users.email_not_found', :email => params[:user][:email])}".html_safe
      respond_to do |format|
        format.html{redirect_to forgot_password_url}
        format.js{render 'alert'}
      end  
    end
  end

  def reset_password
    @user = User.find_using_perishable_token(params[:reset_password_code], 7.days) || not_found
    @title = t('users.reset_password')
  end

  def reset_password_submit  
    @user = User.find_using_perishable_token(params[:reset_password_code], 7.days) || not_found
    if @user.update_attributes(params[:user])
      @user.reset_perishable_token!
      flash[:success] = t('users.reset_password_complete')
      redirect_to login_url
    else
      flash[:error] = t('failure.general')
      render 'reset_password'
    end
  end
end

app/views/admin/users/index.html.haml
.row-fluid
  .span12
    %table.table.table-striped
      %thead
        %tr
          %th= sortable('id', 'ID')
          %th= sortable('login', User.human_attribute_name('login'))
          %th= sortable('email', User.human_attribute_name('email'))
          %th= sortable('active', User.human_attribute_name('active'))
          %th= sortable('banned', User.human_attribute_name('banned'))
          %th= sortable('created_at', User.human_attribute_name('created_at'))
          %th= sortable('updated_at', User.human_attribute_name('updated_at'))  
          %th
      %tbody
        - @items.each do |item|
          %tr
            %td.id= link_to item.id, [:edit, :admin, item]
            %td= link_to item.login, [:edit, :admin, item]
            %td= mail_to item.email
            %td= link_to t("t#{item.active?}"), [:edit, :admin, item]
            %td= link_to t("t#{item.banned?}"), [:edit, :admin, item]
            %td.date= link_to l(item.created_at, :format => :short_date_time), [:edit, :admin, item]
            %td.date= link_to item.created_at == item.updated_at ? t(:never) : l(item.created_at, :format => :short_date_time), [:edit, :admin, item]
            %td.delete= link_to t(:delete), [:admin, item], :method => :delete, :confirm => t(:delete_confirm)
    
    = will_paginate @items, :renderer => BootstrapPaginationRenderer

= content_for :toolbar do
  = link_to t(:add), new_admin_user_path, :class => 'btn btn-large'  

app/views/admin/users/new.html.haml
.row-fluid
  .span9
    = form_for [:admin, @item], :validate => true do |f|
      = render 'form_id', :item => @item
      .control-group
        = f.label :login
        = f.text_field :login, :class => 'input-medium'
      .control-group
        = f.label :email
        = f.text_field :email, :class => 'input-medium'
      .control-group
        = f.label :password
        = f.password_field :password, :class => 'input-medium'
      .control-group
        = f.label :password_confirmation
        = f.password_field :password_confirmation, :class => 'input-medium'
        
      .control-group.form-inline.bottom
        = f.check_box :active
        = f.label :active
      .control-group.form-inline  
        = f.check_box :banned
        = f.label :banned
      .control-group.bottom
        = label_tag t('privilegies.pl')
        .control-group.with-intent
          - unless @item.new_record?
            = hidden_field_tag "user[role_ids][]", Role.find_by_name('registered').id
          - Role.ordered.each do |role|
            - unless role.name == 'registered' || (role.name == 'super_admin' && !has_role?(:super_admin))
              .control-group.form-inline
                = check_box_tag "user[role_ids][]", role.id, @item.role_ids.include?(role.id), :id => "role_#{role.id}"
                = label_tag "role_#{role.id}", t("privilegies.#{role.name}")
      = render 'form_submit_buttons', :f => f
        
  .span3
  
  
= content_for :toolbar do
  = link_to t(:back), [:admin, :users], :class => 'btn btn-medium'